// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CQuestStatusPacket.proto

#include "Proto/CQuestStatusPacket.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Avalon {
namespace Network {
namespace Packets {
namespace Quest {
PROTOBUF_CONSTEXPR CQuestStatusPacket::CQuestStatusPacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.accountid_)*/0
  , /*decltype(_impl_.characterid_)*/0
  , /*decltype(_impl_.questid_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CQuestStatusPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CQuestStatusPacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CQuestStatusPacketDefaultTypeInternal() {}
  union {
    CQuestStatusPacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CQuestStatusPacketDefaultTypeInternal _CQuestStatusPacket_default_instance_;
}  // namespace Quest
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon
static ::_pb::Metadata file_level_metadata_CQuestStatusPacket_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_CQuestStatusPacket_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_CQuestStatusPacket_2eproto = nullptr;

const uint32_t TableStruct_CQuestStatusPacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Quest::CQuestStatusPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Quest::CQuestStatusPacket, _impl_.accountid_),
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Quest::CQuestStatusPacket, _impl_.characterid_),
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Quest::CQuestStatusPacket, _impl_.questid_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Avalon::Network::Packets::Quest::CQuestStatusPacket)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Avalon::Network::Packets::Quest::_CQuestStatusPacket_default_instance_._instance,
};

const char descriptor_table_protodef_CQuestStatusPacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030CQuestStatusPacket.proto\022\034Avalon.Netwo"
  "rk.Packets.Quest\"M\n\022CQuestStatusPacket\022\021"
  "\n\tAccountId\030\001 \001(\005\022\023\n\013CharacterId\030\002 \001(\005\022\017"
  "\n\007QuestId\030\003 \001(\005b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_CQuestStatusPacket_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_CQuestStatusPacket_2eproto = {
    false, false, 143, descriptor_table_protodef_CQuestStatusPacket_2eproto,
    "CQuestStatusPacket.proto",
    &descriptor_table_CQuestStatusPacket_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_CQuestStatusPacket_2eproto::offsets,
    file_level_metadata_CQuestStatusPacket_2eproto, file_level_enum_descriptors_CQuestStatusPacket_2eproto,
    file_level_service_descriptors_CQuestStatusPacket_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_CQuestStatusPacket_2eproto_getter() {
  return &descriptor_table_CQuestStatusPacket_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_CQuestStatusPacket_2eproto(&descriptor_table_CQuestStatusPacket_2eproto);
namespace Avalon {
namespace Network {
namespace Packets {
namespace Quest {

// ===================================================================

class CQuestStatusPacket::_Internal {
 public:
};

CQuestStatusPacket::CQuestStatusPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Avalon.Network.Packets.Quest.CQuestStatusPacket)
}
CQuestStatusPacket::CQuestStatusPacket(const CQuestStatusPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CQuestStatusPacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.accountid_){}
    , decltype(_impl_.characterid_){}
    , decltype(_impl_.questid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.accountid_, &from._impl_.accountid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.questid_) -
    reinterpret_cast<char*>(&_impl_.accountid_)) + sizeof(_impl_.questid_));
  // @@protoc_insertion_point(copy_constructor:Avalon.Network.Packets.Quest.CQuestStatusPacket)
}

inline void CQuestStatusPacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.accountid_){0}
    , decltype(_impl_.characterid_){0}
    , decltype(_impl_.questid_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CQuestStatusPacket::~CQuestStatusPacket() {
  // @@protoc_insertion_point(destructor:Avalon.Network.Packets.Quest.CQuestStatusPacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CQuestStatusPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CQuestStatusPacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CQuestStatusPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:Avalon.Network.Packets.Quest.CQuestStatusPacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.accountid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.questid_) -
      reinterpret_cast<char*>(&_impl_.accountid_)) + sizeof(_impl_.questid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CQuestStatusPacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 AccountId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.accountid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 CharacterId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.characterid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 QuestId = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.questid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CQuestStatusPacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Avalon.Network.Packets.Quest.CQuestStatusPacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 AccountId = 1;
  if (this->_internal_accountid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_accountid(), target);
  }

  // int32 CharacterId = 2;
  if (this->_internal_characterid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_characterid(), target);
  }

  // int32 QuestId = 3;
  if (this->_internal_questid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_questid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Avalon.Network.Packets.Quest.CQuestStatusPacket)
  return target;
}

size_t CQuestStatusPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Avalon.Network.Packets.Quest.CQuestStatusPacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 AccountId = 1;
  if (this->_internal_accountid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_accountid());
  }

  // int32 CharacterId = 2;
  if (this->_internal_characterid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_characterid());
  }

  // int32 QuestId = 3;
  if (this->_internal_questid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_questid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CQuestStatusPacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CQuestStatusPacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CQuestStatusPacket::GetClassData() const { return &_class_data_; }


void CQuestStatusPacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CQuestStatusPacket*>(&to_msg);
  auto& from = static_cast<const CQuestStatusPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Avalon.Network.Packets.Quest.CQuestStatusPacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_accountid() != 0) {
    _this->_internal_set_accountid(from._internal_accountid());
  }
  if (from._internal_characterid() != 0) {
    _this->_internal_set_characterid(from._internal_characterid());
  }
  if (from._internal_questid() != 0) {
    _this->_internal_set_questid(from._internal_questid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CQuestStatusPacket::CopyFrom(const CQuestStatusPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Avalon.Network.Packets.Quest.CQuestStatusPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CQuestStatusPacket::IsInitialized() const {
  return true;
}

void CQuestStatusPacket::InternalSwap(CQuestStatusPacket* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CQuestStatusPacket, _impl_.questid_)
      + sizeof(CQuestStatusPacket::_impl_.questid_)
      - PROTOBUF_FIELD_OFFSET(CQuestStatusPacket, _impl_.accountid_)>(
          reinterpret_cast<char*>(&_impl_.accountid_),
          reinterpret_cast<char*>(&other->_impl_.accountid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CQuestStatusPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_CQuestStatusPacket_2eproto_getter, &descriptor_table_CQuestStatusPacket_2eproto_once,
      file_level_metadata_CQuestStatusPacket_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Quest
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Avalon::Network::Packets::Quest::CQuestStatusPacket*
Arena::CreateMaybeMessage< ::Avalon::Network::Packets::Quest::CQuestStatusPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Avalon::Network::Packets::Quest::CQuestStatusPacket >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
