// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SGroupResultPacket.proto

#include "Proto/SGroupResultPacket.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Avalon {
namespace Network {
namespace Packets {
namespace Social {
PROTOBUF_CONSTEXPR SGroupResultPacket::SGroupResultPacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.accountid_)*/0
  , /*decltype(_impl_.characterid_)*/0
  , /*decltype(_impl_.inviteraccountid_)*/0
  , /*decltype(_impl_.invitercharacterid_)*/0
  , /*decltype(_impl_.accepted_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SGroupResultPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SGroupResultPacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SGroupResultPacketDefaultTypeInternal() {}
  union {
    SGroupResultPacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SGroupResultPacketDefaultTypeInternal _SGroupResultPacket_default_instance_;
}  // namespace Social
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon
static ::_pb::Metadata file_level_metadata_SGroupResultPacket_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_SGroupResultPacket_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_SGroupResultPacket_2eproto = nullptr;

const uint32_t TableStruct_SGroupResultPacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Social::SGroupResultPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Social::SGroupResultPacket, _impl_.accountid_),
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Social::SGroupResultPacket, _impl_.characterid_),
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Social::SGroupResultPacket, _impl_.inviteraccountid_),
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Social::SGroupResultPacket, _impl_.invitercharacterid_),
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Social::SGroupResultPacket, _impl_.accepted_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Avalon::Network::Packets::Social::SGroupResultPacket)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Avalon::Network::Packets::Social::_SGroupResultPacket_default_instance_._instance,
};

const char descriptor_table_protodef_SGroupResultPacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030SGroupResultPacket.proto\022\035Avalon.Netwo"
  "rk.Packets.Social\"\204\001\n\022SGroupResultPacket"
  "\022\021\n\tAccountId\030\001 \001(\005\022\023\n\013CharacterId\030\002 \001(\005"
  "\022\030\n\020InviterAccountId\030\003 \001(\005\022\032\n\022InviterCha"
  "racterId\030\004 \001(\005\022\020\n\010Accepted\030\005 \001(\010b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_SGroupResultPacket_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_SGroupResultPacket_2eproto = {
    false, false, 200, descriptor_table_protodef_SGroupResultPacket_2eproto,
    "SGroupResultPacket.proto",
    &descriptor_table_SGroupResultPacket_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_SGroupResultPacket_2eproto::offsets,
    file_level_metadata_SGroupResultPacket_2eproto, file_level_enum_descriptors_SGroupResultPacket_2eproto,
    file_level_service_descriptors_SGroupResultPacket_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_SGroupResultPacket_2eproto_getter() {
  return &descriptor_table_SGroupResultPacket_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_SGroupResultPacket_2eproto(&descriptor_table_SGroupResultPacket_2eproto);
namespace Avalon {
namespace Network {
namespace Packets {
namespace Social {

// ===================================================================

class SGroupResultPacket::_Internal {
 public:
};

SGroupResultPacket::SGroupResultPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Avalon.Network.Packets.Social.SGroupResultPacket)
}
SGroupResultPacket::SGroupResultPacket(const SGroupResultPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SGroupResultPacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.accountid_){}
    , decltype(_impl_.characterid_){}
    , decltype(_impl_.inviteraccountid_){}
    , decltype(_impl_.invitercharacterid_){}
    , decltype(_impl_.accepted_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.accountid_, &from._impl_.accountid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.accepted_) -
    reinterpret_cast<char*>(&_impl_.accountid_)) + sizeof(_impl_.accepted_));
  // @@protoc_insertion_point(copy_constructor:Avalon.Network.Packets.Social.SGroupResultPacket)
}

inline void SGroupResultPacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.accountid_){0}
    , decltype(_impl_.characterid_){0}
    , decltype(_impl_.inviteraccountid_){0}
    , decltype(_impl_.invitercharacterid_){0}
    , decltype(_impl_.accepted_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SGroupResultPacket::~SGroupResultPacket() {
  // @@protoc_insertion_point(destructor:Avalon.Network.Packets.Social.SGroupResultPacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SGroupResultPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SGroupResultPacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SGroupResultPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:Avalon.Network.Packets.Social.SGroupResultPacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.accountid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.accepted_) -
      reinterpret_cast<char*>(&_impl_.accountid_)) + sizeof(_impl_.accepted_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SGroupResultPacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 AccountId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.accountid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 CharacterId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.characterid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 InviterAccountId = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.inviteraccountid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 InviterCharacterId = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.invitercharacterid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool Accepted = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.accepted_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SGroupResultPacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Avalon.Network.Packets.Social.SGroupResultPacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 AccountId = 1;
  if (this->_internal_accountid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_accountid(), target);
  }

  // int32 CharacterId = 2;
  if (this->_internal_characterid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_characterid(), target);
  }

  // int32 InviterAccountId = 3;
  if (this->_internal_inviteraccountid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_inviteraccountid(), target);
  }

  // int32 InviterCharacterId = 4;
  if (this->_internal_invitercharacterid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_invitercharacterid(), target);
  }

  // bool Accepted = 5;
  if (this->_internal_accepted() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_accepted(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Avalon.Network.Packets.Social.SGroupResultPacket)
  return target;
}

size_t SGroupResultPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Avalon.Network.Packets.Social.SGroupResultPacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 AccountId = 1;
  if (this->_internal_accountid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_accountid());
  }

  // int32 CharacterId = 2;
  if (this->_internal_characterid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_characterid());
  }

  // int32 InviterAccountId = 3;
  if (this->_internal_inviteraccountid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_inviteraccountid());
  }

  // int32 InviterCharacterId = 4;
  if (this->_internal_invitercharacterid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_invitercharacterid());
  }

  // bool Accepted = 5;
  if (this->_internal_accepted() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SGroupResultPacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SGroupResultPacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SGroupResultPacket::GetClassData() const { return &_class_data_; }


void SGroupResultPacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SGroupResultPacket*>(&to_msg);
  auto& from = static_cast<const SGroupResultPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Avalon.Network.Packets.Social.SGroupResultPacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_accountid() != 0) {
    _this->_internal_set_accountid(from._internal_accountid());
  }
  if (from._internal_characterid() != 0) {
    _this->_internal_set_characterid(from._internal_characterid());
  }
  if (from._internal_inviteraccountid() != 0) {
    _this->_internal_set_inviteraccountid(from._internal_inviteraccountid());
  }
  if (from._internal_invitercharacterid() != 0) {
    _this->_internal_set_invitercharacterid(from._internal_invitercharacterid());
  }
  if (from._internal_accepted() != 0) {
    _this->_internal_set_accepted(from._internal_accepted());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SGroupResultPacket::CopyFrom(const SGroupResultPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Avalon.Network.Packets.Social.SGroupResultPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SGroupResultPacket::IsInitialized() const {
  return true;
}

void SGroupResultPacket::InternalSwap(SGroupResultPacket* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SGroupResultPacket, _impl_.accepted_)
      + sizeof(SGroupResultPacket::_impl_.accepted_)
      - PROTOBUF_FIELD_OFFSET(SGroupResultPacket, _impl_.accountid_)>(
          reinterpret_cast<char*>(&_impl_.accountid_),
          reinterpret_cast<char*>(&other->_impl_.accountid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SGroupResultPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SGroupResultPacket_2eproto_getter, &descriptor_table_SGroupResultPacket_2eproto_once,
      file_level_metadata_SGroupResultPacket_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Social
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Avalon::Network::Packets::Social::SGroupResultPacket*
Arena::CreateMaybeMessage< ::Avalon::Network::Packets::Social::SGroupResultPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Avalon::Network::Packets::Social::SGroupResultPacket >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
