// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CHandshakePacket.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_CHandshakePacket_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_CHandshakePacket_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_CHandshakePacket_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_CHandshakePacket_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_CHandshakePacket_2eproto;
namespace Avalon {
namespace Network {
namespace Packets {
namespace Handshake {
class CHandshakePacket;
struct CHandshakePacketDefaultTypeInternal;
extern CHandshakePacketDefaultTypeInternal _CHandshakePacket_default_instance_;
}  // namespace Handshake
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon
PROTOBUF_NAMESPACE_OPEN
template<> ::Avalon::Network::Packets::Handshake::CHandshakePacket* Arena::CreateMaybeMessage<::Avalon::Network::Packets::Handshake::CHandshakePacket>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Avalon {
namespace Network {
namespace Packets {
namespace Handshake {

// ===================================================================

class CHandshakePacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Avalon.Network.Packets.Handshake.CHandshakePacket) */ {
 public:
  inline CHandshakePacket() : CHandshakePacket(nullptr) {}
  ~CHandshakePacket() override;
  explicit PROTOBUF_CONSTEXPR CHandshakePacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CHandshakePacket(const CHandshakePacket& from);
  CHandshakePacket(CHandshakePacket&& from) noexcept
    : CHandshakePacket() {
    *this = ::std::move(from);
  }

  inline CHandshakePacket& operator=(const CHandshakePacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline CHandshakePacket& operator=(CHandshakePacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CHandshakePacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const CHandshakePacket* internal_default_instance() {
    return reinterpret_cast<const CHandshakePacket*>(
               &_CHandshakePacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CHandshakePacket& a, CHandshakePacket& b) {
    a.Swap(&b);
  }
  inline void Swap(CHandshakePacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CHandshakePacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CHandshakePacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CHandshakePacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CHandshakePacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CHandshakePacket& from) {
    CHandshakePacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CHandshakePacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Avalon.Network.Packets.Handshake.CHandshakePacket";
  }
  protected:
  explicit CHandshakePacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHandshakeDataFieldNumber = 1,
  };
  // bytes HandshakeData = 1;
  void clear_handshakedata();
  const std::string& handshakedata() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_handshakedata(ArgT0&& arg0, ArgT... args);
  std::string* mutable_handshakedata();
  PROTOBUF_NODISCARD std::string* release_handshakedata();
  void set_allocated_handshakedata(std::string* handshakedata);
  private:
  const std::string& _internal_handshakedata() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_handshakedata(const std::string& value);
  std::string* _internal_mutable_handshakedata();
  public:

  // @@protoc_insertion_point(class_scope:Avalon.Network.Packets.Handshake.CHandshakePacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr handshakedata_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_CHandshakePacket_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CHandshakePacket

// bytes HandshakeData = 1;
inline void CHandshakePacket::clear_handshakedata() {
  _impl_.handshakedata_.ClearToEmpty();
}
inline const std::string& CHandshakePacket::handshakedata() const {
  // @@protoc_insertion_point(field_get:Avalon.Network.Packets.Handshake.CHandshakePacket.HandshakeData)
  return _internal_handshakedata();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CHandshakePacket::set_handshakedata(ArgT0&& arg0, ArgT... args) {
 
 _impl_.handshakedata_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Avalon.Network.Packets.Handshake.CHandshakePacket.HandshakeData)
}
inline std::string* CHandshakePacket::mutable_handshakedata() {
  std::string* _s = _internal_mutable_handshakedata();
  // @@protoc_insertion_point(field_mutable:Avalon.Network.Packets.Handshake.CHandshakePacket.HandshakeData)
  return _s;
}
inline const std::string& CHandshakePacket::_internal_handshakedata() const {
  return _impl_.handshakedata_.Get();
}
inline void CHandshakePacket::_internal_set_handshakedata(const std::string& value) {
  
  _impl_.handshakedata_.Set(value, GetArenaForAllocation());
}
inline std::string* CHandshakePacket::_internal_mutable_handshakedata() {
  
  return _impl_.handshakedata_.Mutable(GetArenaForAllocation());
}
inline std::string* CHandshakePacket::release_handshakedata() {
  // @@protoc_insertion_point(field_release:Avalon.Network.Packets.Handshake.CHandshakePacket.HandshakeData)
  return _impl_.handshakedata_.Release();
}
inline void CHandshakePacket::set_allocated_handshakedata(std::string* handshakedata) {
  if (handshakedata != nullptr) {
    
  } else {
    
  }
  _impl_.handshakedata_.SetAllocated(handshakedata, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.handshakedata_.IsDefault()) {
    _impl_.handshakedata_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Avalon.Network.Packets.Handshake.CHandshakePacket.HandshakeData)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Handshake
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_CHandshakePacket_2eproto
