// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CQuestListPacket.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_CQuestListPacket_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_CQuestListPacket_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_CQuestListPacket_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_CQuestListPacket_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_CQuestListPacket_2eproto;
namespace Avalon {
namespace Network {
namespace Packets {
namespace Quest {
class CQuestListPacket;
struct CQuestListPacketDefaultTypeInternal;
extern CQuestListPacketDefaultTypeInternal _CQuestListPacket_default_instance_;
}  // namespace Quest
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon
PROTOBUF_NAMESPACE_OPEN
template<> ::Avalon::Network::Packets::Quest::CQuestListPacket* Arena::CreateMaybeMessage<::Avalon::Network::Packets::Quest::CQuestListPacket>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Avalon {
namespace Network {
namespace Packets {
namespace Quest {

// ===================================================================

class CQuestListPacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Avalon.Network.Packets.Quest.CQuestListPacket) */ {
 public:
  inline CQuestListPacket() : CQuestListPacket(nullptr) {}
  ~CQuestListPacket() override;
  explicit PROTOBUF_CONSTEXPR CQuestListPacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CQuestListPacket(const CQuestListPacket& from);
  CQuestListPacket(CQuestListPacket&& from) noexcept
    : CQuestListPacket() {
    *this = ::std::move(from);
  }

  inline CQuestListPacket& operator=(const CQuestListPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline CQuestListPacket& operator=(CQuestListPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CQuestListPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const CQuestListPacket* internal_default_instance() {
    return reinterpret_cast<const CQuestListPacket*>(
               &_CQuestListPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CQuestListPacket& a, CQuestListPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(CQuestListPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CQuestListPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CQuestListPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CQuestListPacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CQuestListPacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CQuestListPacket& from) {
    CQuestListPacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CQuestListPacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Avalon.Network.Packets.Quest.CQuestListPacket";
  }
  protected:
  explicit CQuestListPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIdFieldNumber = 1,
    kCharacterIdFieldNumber = 2,
    kMapIdFieldNumber = 3,
  };
  // int32 AccountId = 1;
  void clear_accountid();
  int32_t accountid() const;
  void set_accountid(int32_t value);
  private:
  int32_t _internal_accountid() const;
  void _internal_set_accountid(int32_t value);
  public:

  // int32 CharacterId = 2;
  void clear_characterid();
  int32_t characterid() const;
  void set_characterid(int32_t value);
  private:
  int32_t _internal_characterid() const;
  void _internal_set_characterid(int32_t value);
  public:

  // int32 MapId = 3;
  void clear_mapid();
  int32_t mapid() const;
  void set_mapid(int32_t value);
  private:
  int32_t _internal_mapid() const;
  void _internal_set_mapid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Avalon.Network.Packets.Quest.CQuestListPacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t accountid_;
    int32_t characterid_;
    int32_t mapid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_CQuestListPacket_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CQuestListPacket

// int32 AccountId = 1;
inline void CQuestListPacket::clear_accountid() {
  _impl_.accountid_ = 0;
}
inline int32_t CQuestListPacket::_internal_accountid() const {
  return _impl_.accountid_;
}
inline int32_t CQuestListPacket::accountid() const {
  // @@protoc_insertion_point(field_get:Avalon.Network.Packets.Quest.CQuestListPacket.AccountId)
  return _internal_accountid();
}
inline void CQuestListPacket::_internal_set_accountid(int32_t value) {
  
  _impl_.accountid_ = value;
}
inline void CQuestListPacket::set_accountid(int32_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:Avalon.Network.Packets.Quest.CQuestListPacket.AccountId)
}

// int32 CharacterId = 2;
inline void CQuestListPacket::clear_characterid() {
  _impl_.characterid_ = 0;
}
inline int32_t CQuestListPacket::_internal_characterid() const {
  return _impl_.characterid_;
}
inline int32_t CQuestListPacket::characterid() const {
  // @@protoc_insertion_point(field_get:Avalon.Network.Packets.Quest.CQuestListPacket.CharacterId)
  return _internal_characterid();
}
inline void CQuestListPacket::_internal_set_characterid(int32_t value) {
  
  _impl_.characterid_ = value;
}
inline void CQuestListPacket::set_characterid(int32_t value) {
  _internal_set_characterid(value);
  // @@protoc_insertion_point(field_set:Avalon.Network.Packets.Quest.CQuestListPacket.CharacterId)
}

// int32 MapId = 3;
inline void CQuestListPacket::clear_mapid() {
  _impl_.mapid_ = 0;
}
inline int32_t CQuestListPacket::_internal_mapid() const {
  return _impl_.mapid_;
}
inline int32_t CQuestListPacket::mapid() const {
  // @@protoc_insertion_point(field_get:Avalon.Network.Packets.Quest.CQuestListPacket.MapId)
  return _internal_mapid();
}
inline void CQuestListPacket::_internal_set_mapid(int32_t value) {
  
  _impl_.mapid_ = value;
}
inline void CQuestListPacket::set_mapid(int32_t value) {
  _internal_set_mapid(value);
  // @@protoc_insertion_point(field_set:Avalon.Network.Packets.Quest.CQuestListPacket.MapId)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Quest
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_CQuestListPacket_2eproto
