// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SChatMessagePacket.proto

#include "SChatMessagePacket.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Avalon {
namespace Network {
namespace Packets {
namespace Social {
PROTOBUF_CONSTEXPR SChatMessagePacket::SChatMessagePacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.charactername_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.datetime_)*/nullptr
  , /*decltype(_impl_.accountid_)*/0
  , /*decltype(_impl_.characterid_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SChatMessagePacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SChatMessagePacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SChatMessagePacketDefaultTypeInternal() {}
  union {
    SChatMessagePacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SChatMessagePacketDefaultTypeInternal _SChatMessagePacket_default_instance_;
}  // namespace Social
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon
static ::_pb::Metadata file_level_metadata_SChatMessagePacket_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_SChatMessagePacket_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_SChatMessagePacket_2eproto = nullptr;

const uint32_t TableStruct_SChatMessagePacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Social::SChatMessagePacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Social::SChatMessagePacket, _impl_.accountid_),
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Social::SChatMessagePacket, _impl_.characterid_),
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Social::SChatMessagePacket, _impl_.charactername_),
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Social::SChatMessagePacket, _impl_.message_),
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Social::SChatMessagePacket, _impl_.datetime_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Avalon::Network::Packets::Social::SChatMessagePacket)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Avalon::Network::Packets::Social::_SChatMessagePacket_default_instance_._instance,
};

const char descriptor_table_protodef_SChatMessagePacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030SChatMessagePacket.proto\022\035Avalon.Netwo"
  "rk.Packets.Social\032\tbcl.proto\"\205\001\n\022SChatMe"
  "ssagePacket\022\021\n\tAccountId\030\001 \001(\005\022\023\n\013Charac"
  "terId\030\002 \001(\005\022\025\n\rCharacterName\030\003 \001(\t\022\017\n\007Me"
  "ssage\030\004 \001(\t\022\037\n\010DateTime\030\005 \001(\0132\r.bcl.Date"
  "Timeb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_SChatMessagePacket_2eproto_deps[1] = {
  &::descriptor_table_bcl_2eproto,
};
static ::_pbi::once_flag descriptor_table_SChatMessagePacket_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_SChatMessagePacket_2eproto = {
    false, false, 212, descriptor_table_protodef_SChatMessagePacket_2eproto,
    "SChatMessagePacket.proto",
    &descriptor_table_SChatMessagePacket_2eproto_once, descriptor_table_SChatMessagePacket_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_SChatMessagePacket_2eproto::offsets,
    file_level_metadata_SChatMessagePacket_2eproto, file_level_enum_descriptors_SChatMessagePacket_2eproto,
    file_level_service_descriptors_SChatMessagePacket_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_SChatMessagePacket_2eproto_getter() {
  return &descriptor_table_SChatMessagePacket_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_SChatMessagePacket_2eproto(&descriptor_table_SChatMessagePacket_2eproto);
namespace Avalon {
namespace Network {
namespace Packets {
namespace Social {

// ===================================================================

class SChatMessagePacket::_Internal {
 public:
  static const ::bcl::DateTime& datetime(const SChatMessagePacket* msg);
};

const ::bcl::DateTime&
SChatMessagePacket::_Internal::datetime(const SChatMessagePacket* msg) {
  return *msg->_impl_.datetime_;
}
void SChatMessagePacket::clear_datetime() {
  if (GetArenaForAllocation() == nullptr && _impl_.datetime_ != nullptr) {
    delete _impl_.datetime_;
  }
  _impl_.datetime_ = nullptr;
}
SChatMessagePacket::SChatMessagePacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Avalon.Network.Packets.Social.SChatMessagePacket)
}
SChatMessagePacket::SChatMessagePacket(const SChatMessagePacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SChatMessagePacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.charactername_){}
    , decltype(_impl_.message_){}
    , decltype(_impl_.datetime_){nullptr}
    , decltype(_impl_.accountid_){}
    , decltype(_impl_.characterid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.charactername_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.charactername_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_charactername().empty()) {
    _this->_impl_.charactername_.Set(from._internal_charactername(), 
      _this->GetArenaForAllocation());
  }
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_datetime()) {
    _this->_impl_.datetime_ = new ::bcl::DateTime(*from._impl_.datetime_);
  }
  ::memcpy(&_impl_.accountid_, &from._impl_.accountid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.characterid_) -
    reinterpret_cast<char*>(&_impl_.accountid_)) + sizeof(_impl_.characterid_));
  // @@protoc_insertion_point(copy_constructor:Avalon.Network.Packets.Social.SChatMessagePacket)
}

inline void SChatMessagePacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.charactername_){}
    , decltype(_impl_.message_){}
    , decltype(_impl_.datetime_){nullptr}
    , decltype(_impl_.accountid_){0}
    , decltype(_impl_.characterid_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.charactername_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.charactername_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SChatMessagePacket::~SChatMessagePacket() {
  // @@protoc_insertion_point(destructor:Avalon.Network.Packets.Social.SChatMessagePacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SChatMessagePacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.charactername_.Destroy();
  _impl_.message_.Destroy();
  if (this != internal_default_instance()) delete _impl_.datetime_;
}

void SChatMessagePacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SChatMessagePacket::Clear() {
// @@protoc_insertion_point(message_clear_start:Avalon.Network.Packets.Social.SChatMessagePacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.charactername_.ClearToEmpty();
  _impl_.message_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.datetime_ != nullptr) {
    delete _impl_.datetime_;
  }
  _impl_.datetime_ = nullptr;
  ::memset(&_impl_.accountid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.characterid_) -
      reinterpret_cast<char*>(&_impl_.accountid_)) + sizeof(_impl_.characterid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SChatMessagePacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 AccountId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.accountid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 CharacterId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.characterid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string CharacterName = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_charactername();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Avalon.Network.Packets.Social.SChatMessagePacket.CharacterName"));
        } else
          goto handle_unusual;
        continue;
      // string Message = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Avalon.Network.Packets.Social.SChatMessagePacket.Message"));
        } else
          goto handle_unusual;
        continue;
      // .bcl.DateTime DateTime = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_datetime(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SChatMessagePacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Avalon.Network.Packets.Social.SChatMessagePacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 AccountId = 1;
  if (this->_internal_accountid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_accountid(), target);
  }

  // int32 CharacterId = 2;
  if (this->_internal_characterid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_characterid(), target);
  }

  // string CharacterName = 3;
  if (!this->_internal_charactername().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_charactername().data(), static_cast<int>(this->_internal_charactername().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Avalon.Network.Packets.Social.SChatMessagePacket.CharacterName");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_charactername(), target);
  }

  // string Message = 4;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Avalon.Network.Packets.Social.SChatMessagePacket.Message");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_message(), target);
  }

  // .bcl.DateTime DateTime = 5;
  if (this->_internal_has_datetime()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::datetime(this),
        _Internal::datetime(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Avalon.Network.Packets.Social.SChatMessagePacket)
  return target;
}

size_t SChatMessagePacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Avalon.Network.Packets.Social.SChatMessagePacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string CharacterName = 3;
  if (!this->_internal_charactername().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_charactername());
  }

  // string Message = 4;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // .bcl.DateTime DateTime = 5;
  if (this->_internal_has_datetime()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.datetime_);
  }

  // int32 AccountId = 1;
  if (this->_internal_accountid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_accountid());
  }

  // int32 CharacterId = 2;
  if (this->_internal_characterid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_characterid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SChatMessagePacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SChatMessagePacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SChatMessagePacket::GetClassData() const { return &_class_data_; }


void SChatMessagePacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SChatMessagePacket*>(&to_msg);
  auto& from = static_cast<const SChatMessagePacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Avalon.Network.Packets.Social.SChatMessagePacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_charactername().empty()) {
    _this->_internal_set_charactername(from._internal_charactername());
  }
  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_has_datetime()) {
    _this->_internal_mutable_datetime()->::bcl::DateTime::MergeFrom(
        from._internal_datetime());
  }
  if (from._internal_accountid() != 0) {
    _this->_internal_set_accountid(from._internal_accountid());
  }
  if (from._internal_characterid() != 0) {
    _this->_internal_set_characterid(from._internal_characterid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SChatMessagePacket::CopyFrom(const SChatMessagePacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Avalon.Network.Packets.Social.SChatMessagePacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SChatMessagePacket::IsInitialized() const {
  return true;
}

void SChatMessagePacket::InternalSwap(SChatMessagePacket* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.charactername_, lhs_arena,
      &other->_impl_.charactername_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SChatMessagePacket, _impl_.characterid_)
      + sizeof(SChatMessagePacket::_impl_.characterid_)
      - PROTOBUF_FIELD_OFFSET(SChatMessagePacket, _impl_.datetime_)>(
          reinterpret_cast<char*>(&_impl_.datetime_),
          reinterpret_cast<char*>(&other->_impl_.datetime_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SChatMessagePacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SChatMessagePacket_2eproto_getter, &descriptor_table_SChatMessagePacket_2eproto_once,
      file_level_metadata_SChatMessagePacket_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Social
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Avalon::Network::Packets::Social::SChatMessagePacket*
Arena::CreateMaybeMessage< ::Avalon::Network::Packets::Social::SChatMessagePacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Avalon::Network::Packets::Social::SChatMessagePacket >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
