// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SLogoutPacket.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_SLogoutPacket_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_SLogoutPacket_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SLogoutPacket_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_SLogoutPacket_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_SLogoutPacket_2eproto;
namespace Avalon {
namespace Network {
namespace Packets {
namespace Auth {
class SLogoutPacket;
struct SLogoutPacketDefaultTypeInternal;
extern SLogoutPacketDefaultTypeInternal _SLogoutPacket_default_instance_;
}  // namespace Auth
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon
PROTOBUF_NAMESPACE_OPEN
template<> ::Avalon::Network::Packets::Auth::SLogoutPacket* Arena::CreateMaybeMessage<::Avalon::Network::Packets::Auth::SLogoutPacket>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Avalon {
namespace Network {
namespace Packets {
namespace Auth {

enum LogoutResult : int {
  Success = 0,
  RecentlyInCombat = 1,
  NotInGame = 2,
  NotSameAccount = 3,
  InternalError = 4,
  LogoutResult_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  LogoutResult_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool LogoutResult_IsValid(int value);
constexpr LogoutResult LogoutResult_MIN = Success;
constexpr LogoutResult LogoutResult_MAX = InternalError;
constexpr int LogoutResult_ARRAYSIZE = LogoutResult_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LogoutResult_descriptor();
template<typename T>
inline const std::string& LogoutResult_Name(T enum_t_value) {
  static_assert(::std::is_same<T, LogoutResult>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function LogoutResult_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    LogoutResult_descriptor(), enum_t_value);
}
inline bool LogoutResult_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LogoutResult* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LogoutResult>(
    LogoutResult_descriptor(), name, value);
}
// ===================================================================

class SLogoutPacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Avalon.Network.Packets.Auth.SLogoutPacket) */ {
 public:
  inline SLogoutPacket() : SLogoutPacket(nullptr) {}
  ~SLogoutPacket() override;
  explicit PROTOBUF_CONSTEXPR SLogoutPacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SLogoutPacket(const SLogoutPacket& from);
  SLogoutPacket(SLogoutPacket&& from) noexcept
    : SLogoutPacket() {
    *this = ::std::move(from);
  }

  inline SLogoutPacket& operator=(const SLogoutPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline SLogoutPacket& operator=(SLogoutPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SLogoutPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const SLogoutPacket* internal_default_instance() {
    return reinterpret_cast<const SLogoutPacket*>(
               &_SLogoutPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SLogoutPacket& a, SLogoutPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(SLogoutPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SLogoutPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SLogoutPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SLogoutPacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SLogoutPacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SLogoutPacket& from) {
    SLogoutPacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SLogoutPacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Avalon.Network.Packets.Auth.SLogoutPacket";
  }
  protected:
  explicit SLogoutPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIdFieldNumber = 1,
    kResultFieldNumber = 2,
  };
  // int32 AccountId = 1;
  void clear_accountid();
  int32_t accountid() const;
  void set_accountid(int32_t value);
  private:
  int32_t _internal_accountid() const;
  void _internal_set_accountid(int32_t value);
  public:

  // .Avalon.Network.Packets.Auth.LogoutResult Result = 2;
  void clear_result();
  ::Avalon::Network::Packets::Auth::LogoutResult result() const;
  void set_result(::Avalon::Network::Packets::Auth::LogoutResult value);
  private:
  ::Avalon::Network::Packets::Auth::LogoutResult _internal_result() const;
  void _internal_set_result(::Avalon::Network::Packets::Auth::LogoutResult value);
  public:

  // @@protoc_insertion_point(class_scope:Avalon.Network.Packets.Auth.SLogoutPacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t accountid_;
    int result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SLogoutPacket_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SLogoutPacket

// int32 AccountId = 1;
inline void SLogoutPacket::clear_accountid() {
  _impl_.accountid_ = 0;
}
inline int32_t SLogoutPacket::_internal_accountid() const {
  return _impl_.accountid_;
}
inline int32_t SLogoutPacket::accountid() const {
  // @@protoc_insertion_point(field_get:Avalon.Network.Packets.Auth.SLogoutPacket.AccountId)
  return _internal_accountid();
}
inline void SLogoutPacket::_internal_set_accountid(int32_t value) {
  
  _impl_.accountid_ = value;
}
inline void SLogoutPacket::set_accountid(int32_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:Avalon.Network.Packets.Auth.SLogoutPacket.AccountId)
}

// .Avalon.Network.Packets.Auth.LogoutResult Result = 2;
inline void SLogoutPacket::clear_result() {
  _impl_.result_ = 0;
}
inline ::Avalon::Network::Packets::Auth::LogoutResult SLogoutPacket::_internal_result() const {
  return static_cast< ::Avalon::Network::Packets::Auth::LogoutResult >(_impl_.result_);
}
inline ::Avalon::Network::Packets::Auth::LogoutResult SLogoutPacket::result() const {
  // @@protoc_insertion_point(field_get:Avalon.Network.Packets.Auth.SLogoutPacket.Result)
  return _internal_result();
}
inline void SLogoutPacket::_internal_set_result(::Avalon::Network::Packets::Auth::LogoutResult value) {
  
  _impl_.result_ = value;
}
inline void SLogoutPacket::set_result(::Avalon::Network::Packets::Auth::LogoutResult value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:Avalon.Network.Packets.Auth.SLogoutPacket.Result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Auth
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Avalon::Network::Packets::Auth::LogoutResult> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Avalon::Network::Packets::Auth::LogoutResult>() {
  return ::Avalon::Network::Packets::Auth::LogoutResult_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_SLogoutPacket_2eproto
