// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SPingPacket.proto

#include "SPingPacket.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Avalon {
namespace Network {
namespace Packets {
namespace Generic {
PROTOBUF_CONSTEXPR SPingPacket::SPingPacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.sequencenumber_)*/int64_t{0}
  , /*decltype(_impl_.ticks_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SPingPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SPingPacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SPingPacketDefaultTypeInternal() {}
  union {
    SPingPacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SPingPacketDefaultTypeInternal _SPingPacket_default_instance_;
}  // namespace Generic
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon
static ::_pb::Metadata file_level_metadata_SPingPacket_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_SPingPacket_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_SPingPacket_2eproto = nullptr;

const uint32_t TableStruct_SPingPacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Generic::SPingPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Generic::SPingPacket, _impl_.sequencenumber_),
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Generic::SPingPacket, _impl_.ticks_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Avalon::Network::Packets::Generic::SPingPacket)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Avalon::Network::Packets::Generic::_SPingPacket_default_instance_._instance,
};

const char descriptor_table_protodef_SPingPacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021SPingPacket.proto\022\036Avalon.Network.Pack"
  "ets.Generic\"4\n\013SPingPacket\022\026\n\016SequenceNu"
  "mber\030\001 \001(\003\022\r\n\005Ticks\030\002 \001(\003b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_SPingPacket_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_SPingPacket_2eproto = {
    false, false, 113, descriptor_table_protodef_SPingPacket_2eproto,
    "SPingPacket.proto",
    &descriptor_table_SPingPacket_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_SPingPacket_2eproto::offsets,
    file_level_metadata_SPingPacket_2eproto, file_level_enum_descriptors_SPingPacket_2eproto,
    file_level_service_descriptors_SPingPacket_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_SPingPacket_2eproto_getter() {
  return &descriptor_table_SPingPacket_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_SPingPacket_2eproto(&descriptor_table_SPingPacket_2eproto);
namespace Avalon {
namespace Network {
namespace Packets {
namespace Generic {

// ===================================================================

class SPingPacket::_Internal {
 public:
};

SPingPacket::SPingPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Avalon.Network.Packets.Generic.SPingPacket)
}
SPingPacket::SPingPacket(const SPingPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SPingPacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.sequencenumber_){}
    , decltype(_impl_.ticks_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.sequencenumber_, &from._impl_.sequencenumber_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.ticks_) -
    reinterpret_cast<char*>(&_impl_.sequencenumber_)) + sizeof(_impl_.ticks_));
  // @@protoc_insertion_point(copy_constructor:Avalon.Network.Packets.Generic.SPingPacket)
}

inline void SPingPacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.sequencenumber_){int64_t{0}}
    , decltype(_impl_.ticks_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SPingPacket::~SPingPacket() {
  // @@protoc_insertion_point(destructor:Avalon.Network.Packets.Generic.SPingPacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SPingPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SPingPacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SPingPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:Avalon.Network.Packets.Generic.SPingPacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.sequencenumber_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.ticks_) -
      reinterpret_cast<char*>(&_impl_.sequencenumber_)) + sizeof(_impl_.ticks_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SPingPacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 SequenceNumber = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.sequencenumber_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 Ticks = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.ticks_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SPingPacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Avalon.Network.Packets.Generic.SPingPacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 SequenceNumber = 1;
  if (this->_internal_sequencenumber() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_sequencenumber(), target);
  }

  // int64 Ticks = 2;
  if (this->_internal_ticks() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_ticks(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Avalon.Network.Packets.Generic.SPingPacket)
  return target;
}

size_t SPingPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Avalon.Network.Packets.Generic.SPingPacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 SequenceNumber = 1;
  if (this->_internal_sequencenumber() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_sequencenumber());
  }

  // int64 Ticks = 2;
  if (this->_internal_ticks() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_ticks());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SPingPacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SPingPacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SPingPacket::GetClassData() const { return &_class_data_; }


void SPingPacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SPingPacket*>(&to_msg);
  auto& from = static_cast<const SPingPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Avalon.Network.Packets.Generic.SPingPacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_sequencenumber() != 0) {
    _this->_internal_set_sequencenumber(from._internal_sequencenumber());
  }
  if (from._internal_ticks() != 0) {
    _this->_internal_set_ticks(from._internal_ticks());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SPingPacket::CopyFrom(const SPingPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Avalon.Network.Packets.Generic.SPingPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SPingPacket::IsInitialized() const {
  return true;
}

void SPingPacket::InternalSwap(SPingPacket* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SPingPacket, _impl_.ticks_)
      + sizeof(SPingPacket::_impl_.ticks_)
      - PROTOBUF_FIELD_OFFSET(SPingPacket, _impl_.sequencenumber_)>(
          reinterpret_cast<char*>(&_impl_.sequencenumber_),
          reinterpret_cast<char*>(&other->_impl_.sequencenumber_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SPingPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SPingPacket_2eproto_getter, &descriptor_table_SPingPacket_2eproto_once,
      file_level_metadata_SPingPacket_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Generic
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Avalon::Network::Packets::Generic::SPingPacket*
Arena::CreateMaybeMessage< ::Avalon::Network::Packets::Generic::SPingPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Avalon::Network::Packets::Generic::SPingPacket >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
