// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SRegisterResultPacket.proto

#include "SRegisterResultPacket.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Avalon {
namespace Network {
namespace Packets {
namespace Auth {
PROTOBUF_CONSTEXPR SRegisterResultPacket::SRegisterResultPacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.result_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SRegisterResultPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SRegisterResultPacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SRegisterResultPacketDefaultTypeInternal() {}
  union {
    SRegisterResultPacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SRegisterResultPacketDefaultTypeInternal _SRegisterResultPacket_default_instance_;
}  // namespace Auth
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon
static ::_pb::Metadata file_level_metadata_SRegisterResultPacket_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_SRegisterResultPacket_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_SRegisterResultPacket_2eproto = nullptr;

const uint32_t TableStruct_SRegisterResultPacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Auth::SRegisterResultPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Avalon::Network::Packets::Auth::SRegisterResultPacket, _impl_.result_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Avalon::Network::Packets::Auth::SRegisterResultPacket)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Avalon::Network::Packets::Auth::_SRegisterResultPacket_default_instance_._instance,
};

const char descriptor_table_protodef_SRegisterResultPacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033SRegisterResultPacket.proto\022\033Avalon.Ne"
  "twork.Packets.Auth\"T\n\025SRegisterResultPac"
  "ket\022;\n\006Result\030\001 \001(\0162+.Avalon.Network.Pac"
  "kets.Auth.RegisterResult*\270\001\n\016RegisterRes"
  "ult\022\020\n\014UnknownError\020\000\022\021\n\rEmptyUsername\020\001"
  "\022\021\n\rEmptyPassword\020\002\022\025\n\021DuplicateUsername"
  "\020\003\022\022\n\016DuplicateEmail\020\004\022\024\n\020PasswordTooSho"
  "rt\020\005\022\023\n\017PasswordTooLong\020\006\022\020\n\014InvalidEmai"
  "l\020\007\022\006\n\002Ok\020\010b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_SRegisterResultPacket_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_SRegisterResultPacket_2eproto = {
    false, false, 339, descriptor_table_protodef_SRegisterResultPacket_2eproto,
    "SRegisterResultPacket.proto",
    &descriptor_table_SRegisterResultPacket_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_SRegisterResultPacket_2eproto::offsets,
    file_level_metadata_SRegisterResultPacket_2eproto, file_level_enum_descriptors_SRegisterResultPacket_2eproto,
    file_level_service_descriptors_SRegisterResultPacket_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_SRegisterResultPacket_2eproto_getter() {
  return &descriptor_table_SRegisterResultPacket_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_SRegisterResultPacket_2eproto(&descriptor_table_SRegisterResultPacket_2eproto);
namespace Avalon {
namespace Network {
namespace Packets {
namespace Auth {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RegisterResult_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_SRegisterResultPacket_2eproto);
  return file_level_enum_descriptors_SRegisterResultPacket_2eproto[0];
}
bool RegisterResult_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class SRegisterResultPacket::_Internal {
 public:
};

SRegisterResultPacket::SRegisterResultPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Avalon.Network.Packets.Auth.SRegisterResultPacket)
}
SRegisterResultPacket::SRegisterResultPacket(const SRegisterResultPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SRegisterResultPacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.result_ = from._impl_.result_;
  // @@protoc_insertion_point(copy_constructor:Avalon.Network.Packets.Auth.SRegisterResultPacket)
}

inline void SRegisterResultPacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SRegisterResultPacket::~SRegisterResultPacket() {
  // @@protoc_insertion_point(destructor:Avalon.Network.Packets.Auth.SRegisterResultPacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SRegisterResultPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SRegisterResultPacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SRegisterResultPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:Avalon.Network.Packets.Auth.SRegisterResultPacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SRegisterResultPacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Avalon.Network.Packets.Auth.RegisterResult Result = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_result(static_cast<::Avalon::Network::Packets::Auth::RegisterResult>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SRegisterResultPacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Avalon.Network.Packets.Auth.SRegisterResultPacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Avalon.Network.Packets.Auth.RegisterResult Result = 1;
  if (this->_internal_result() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_result(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Avalon.Network.Packets.Auth.SRegisterResultPacket)
  return target;
}

size_t SRegisterResultPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Avalon.Network.Packets.Auth.SRegisterResultPacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Avalon.Network.Packets.Auth.RegisterResult Result = 1;
  if (this->_internal_result() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_result());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SRegisterResultPacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SRegisterResultPacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SRegisterResultPacket::GetClassData() const { return &_class_data_; }


void SRegisterResultPacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SRegisterResultPacket*>(&to_msg);
  auto& from = static_cast<const SRegisterResultPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Avalon.Network.Packets.Auth.SRegisterResultPacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_result() != 0) {
    _this->_internal_set_result(from._internal_result());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SRegisterResultPacket::CopyFrom(const SRegisterResultPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Avalon.Network.Packets.Auth.SRegisterResultPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SRegisterResultPacket::IsInitialized() const {
  return true;
}

void SRegisterResultPacket::InternalSwap(SRegisterResultPacket* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.result_, other->_impl_.result_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SRegisterResultPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SRegisterResultPacket_2eproto_getter, &descriptor_table_SRegisterResultPacket_2eproto_once,
      file_level_metadata_SRegisterResultPacket_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Auth
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Avalon::Network::Packets::Auth::SRegisterResultPacket*
Arena::CreateMaybeMessage< ::Avalon::Network::Packets::Auth::SRegisterResultPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Avalon::Network::Packets::Auth::SRegisterResultPacket >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
