// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SGroupInvitePacket.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_SGroupInvitePacket_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_SGroupInvitePacket_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SGroupInvitePacket_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_SGroupInvitePacket_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_SGroupInvitePacket_2eproto;
namespace Avalon {
namespace Network {
namespace Packets {
namespace Social {
class SGroupInvitePacket;
struct SGroupInvitePacketDefaultTypeInternal;
extern SGroupInvitePacketDefaultTypeInternal _SGroupInvitePacket_default_instance_;
}  // namespace Social
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon
PROTOBUF_NAMESPACE_OPEN
template<> ::Avalon::Network::Packets::Social::SGroupInvitePacket* Arena::CreateMaybeMessage<::Avalon::Network::Packets::Social::SGroupInvitePacket>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Avalon {
namespace Network {
namespace Packets {
namespace Social {

// ===================================================================

class SGroupInvitePacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Avalon.Network.Packets.Social.SGroupInvitePacket) */ {
 public:
  inline SGroupInvitePacket() : SGroupInvitePacket(nullptr) {}
  ~SGroupInvitePacket() override;
  explicit PROTOBUF_CONSTEXPR SGroupInvitePacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SGroupInvitePacket(const SGroupInvitePacket& from);
  SGroupInvitePacket(SGroupInvitePacket&& from) noexcept
    : SGroupInvitePacket() {
    *this = ::std::move(from);
  }

  inline SGroupInvitePacket& operator=(const SGroupInvitePacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline SGroupInvitePacket& operator=(SGroupInvitePacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SGroupInvitePacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const SGroupInvitePacket* internal_default_instance() {
    return reinterpret_cast<const SGroupInvitePacket*>(
               &_SGroupInvitePacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SGroupInvitePacket& a, SGroupInvitePacket& b) {
    a.Swap(&b);
  }
  inline void Swap(SGroupInvitePacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SGroupInvitePacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SGroupInvitePacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SGroupInvitePacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SGroupInvitePacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SGroupInvitePacket& from) {
    SGroupInvitePacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SGroupInvitePacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Avalon.Network.Packets.Social.SGroupInvitePacket";
  }
  protected:
  explicit SGroupInvitePacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInviterNameFieldNumber = 4,
    kAccountIdFieldNumber = 1,
    kInviterAccountIdFieldNumber = 2,
    kInviterCharacterIdFieldNumber = 3,
  };
  // string InviterName = 4;
  void clear_invitername();
  const std::string& invitername() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_invitername(ArgT0&& arg0, ArgT... args);
  std::string* mutable_invitername();
  PROTOBUF_NODISCARD std::string* release_invitername();
  void set_allocated_invitername(std::string* invitername);
  private:
  const std::string& _internal_invitername() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_invitername(const std::string& value);
  std::string* _internal_mutable_invitername();
  public:

  // int32 AccountId = 1;
  void clear_accountid();
  int32_t accountid() const;
  void set_accountid(int32_t value);
  private:
  int32_t _internal_accountid() const;
  void _internal_set_accountid(int32_t value);
  public:

  // int32 InviterAccountId = 2;
  void clear_inviteraccountid();
  int32_t inviteraccountid() const;
  void set_inviteraccountid(int32_t value);
  private:
  int32_t _internal_inviteraccountid() const;
  void _internal_set_inviteraccountid(int32_t value);
  public:

  // int32 InviterCharacterId = 3;
  void clear_invitercharacterid();
  int32_t invitercharacterid() const;
  void set_invitercharacterid(int32_t value);
  private:
  int32_t _internal_invitercharacterid() const;
  void _internal_set_invitercharacterid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Avalon.Network.Packets.Social.SGroupInvitePacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr invitername_;
    int32_t accountid_;
    int32_t inviteraccountid_;
    int32_t invitercharacterid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SGroupInvitePacket_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SGroupInvitePacket

// int32 AccountId = 1;
inline void SGroupInvitePacket::clear_accountid() {
  _impl_.accountid_ = 0;
}
inline int32_t SGroupInvitePacket::_internal_accountid() const {
  return _impl_.accountid_;
}
inline int32_t SGroupInvitePacket::accountid() const {
  // @@protoc_insertion_point(field_get:Avalon.Network.Packets.Social.SGroupInvitePacket.AccountId)
  return _internal_accountid();
}
inline void SGroupInvitePacket::_internal_set_accountid(int32_t value) {
  
  _impl_.accountid_ = value;
}
inline void SGroupInvitePacket::set_accountid(int32_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:Avalon.Network.Packets.Social.SGroupInvitePacket.AccountId)
}

// int32 InviterAccountId = 2;
inline void SGroupInvitePacket::clear_inviteraccountid() {
  _impl_.inviteraccountid_ = 0;
}
inline int32_t SGroupInvitePacket::_internal_inviteraccountid() const {
  return _impl_.inviteraccountid_;
}
inline int32_t SGroupInvitePacket::inviteraccountid() const {
  // @@protoc_insertion_point(field_get:Avalon.Network.Packets.Social.SGroupInvitePacket.InviterAccountId)
  return _internal_inviteraccountid();
}
inline void SGroupInvitePacket::_internal_set_inviteraccountid(int32_t value) {
  
  _impl_.inviteraccountid_ = value;
}
inline void SGroupInvitePacket::set_inviteraccountid(int32_t value) {
  _internal_set_inviteraccountid(value);
  // @@protoc_insertion_point(field_set:Avalon.Network.Packets.Social.SGroupInvitePacket.InviterAccountId)
}

// int32 InviterCharacterId = 3;
inline void SGroupInvitePacket::clear_invitercharacterid() {
  _impl_.invitercharacterid_ = 0;
}
inline int32_t SGroupInvitePacket::_internal_invitercharacterid() const {
  return _impl_.invitercharacterid_;
}
inline int32_t SGroupInvitePacket::invitercharacterid() const {
  // @@protoc_insertion_point(field_get:Avalon.Network.Packets.Social.SGroupInvitePacket.InviterCharacterId)
  return _internal_invitercharacterid();
}
inline void SGroupInvitePacket::_internal_set_invitercharacterid(int32_t value) {
  
  _impl_.invitercharacterid_ = value;
}
inline void SGroupInvitePacket::set_invitercharacterid(int32_t value) {
  _internal_set_invitercharacterid(value);
  // @@protoc_insertion_point(field_set:Avalon.Network.Packets.Social.SGroupInvitePacket.InviterCharacterId)
}

// string InviterName = 4;
inline void SGroupInvitePacket::clear_invitername() {
  _impl_.invitername_.ClearToEmpty();
}
inline const std::string& SGroupInvitePacket::invitername() const {
  // @@protoc_insertion_point(field_get:Avalon.Network.Packets.Social.SGroupInvitePacket.InviterName)
  return _internal_invitername();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SGroupInvitePacket::set_invitername(ArgT0&& arg0, ArgT... args) {
 
 _impl_.invitername_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Avalon.Network.Packets.Social.SGroupInvitePacket.InviterName)
}
inline std::string* SGroupInvitePacket::mutable_invitername() {
  std::string* _s = _internal_mutable_invitername();
  // @@protoc_insertion_point(field_mutable:Avalon.Network.Packets.Social.SGroupInvitePacket.InviterName)
  return _s;
}
inline const std::string& SGroupInvitePacket::_internal_invitername() const {
  return _impl_.invitername_.Get();
}
inline void SGroupInvitePacket::_internal_set_invitername(const std::string& value) {
  
  _impl_.invitername_.Set(value, GetArenaForAllocation());
}
inline std::string* SGroupInvitePacket::_internal_mutable_invitername() {
  
  return _impl_.invitername_.Mutable(GetArenaForAllocation());
}
inline std::string* SGroupInvitePacket::release_invitername() {
  // @@protoc_insertion_point(field_release:Avalon.Network.Packets.Social.SGroupInvitePacket.InviterName)
  return _impl_.invitername_.Release();
}
inline void SGroupInvitePacket::set_allocated_invitername(std::string* invitername) {
  if (invitername != nullptr) {
    
  } else {
    
  }
  _impl_.invitername_.SetAllocated(invitername, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.invitername_.IsDefault()) {
    _impl_.invitername_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Avalon.Network.Packets.Social.SGroupInvitePacket.InviterName)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Social
}  // namespace Packets
}  // namespace Network
}  // namespace Avalon

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_SGroupInvitePacket_2eproto
